FROM node:18

# Set working directory
WORKDIR /gateway

# Copy all files
COPY . .
COPY start.sh /start.sh

RUN chmod +x start.sh
# Install dependencies
RUN apt-get update && apt-get install -y curl
RUN npm install

# Compile TypeScript to dist/
RUN npm run build

# Expose the gateway port
EXPOSE 4000

# Start the built app
CMD ["/start.sh", "npm", "run", "start"]
