"""blogdetails added

Revision ID: 0a0eb61c74bb
Revises: 
Create Date: 2025-07-14 11:57:21.297247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a0eb61c74bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_details',
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, serve_onupdate=sa.text('now()')),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True, serve_onupdate=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_like_details',
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, serve_onupdate=sa.text('now()')),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True, serve_onupdate=sa.text('now()')),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_like_details')
    op.drop_table('blog_details')
    # ### end Alembic commands ###
