"""empty message

Revision ID: 96c8965ce084
Revises: bc1d9cefcf8b
Create Date: 2025-07-21 14:56:13.654930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c8965ce084'
down_revision: Union[str, None] = 'bc1d9cefcf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_like_details', sa.Column('is_liked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_like_details', 'is_liked')
    # ### end Alembic commands ###
